/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as PharmacieRouteImport } from './routes/pharmacie'
import { Route as PortailRouteImport } from './routes/portail'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TransmissionsRouteImport } from './routes/transmissions'
import { Route as ModulesSlugRouteImport } from './routes/modules.$slug'
import { Route as PharmacieIndexRouteImport } from './routes/pharmacie.index'
import { Route as PharmacieChecklistRouteImport } from './routes/pharmacie.checklist'
import { Route as PharmacieComparatifRouteImport } from './routes/pharmacie.comparatif'
import { Route as PharmacieFichesRouteImport } from './routes/pharmacie.fiches'
import { Route as PharmacieSignalementsRouteImport } from './routes/pharmacie.signalements'
import { Route as ApiPublicPharmaFichesCronRouteImport } from './routes/api/public/pharma-fiches-cron'
import { Route as PharmacieFicheSlugRouteImport } from './routes/pharmacie.fiche.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacieRoute = PharmacieRouteImport.update({
  id: '/pharmacie',
  path: '/pharmacie',
  getParentRoute: () => rootRouteImport,
} as any)
const PortailRoute = PortailRouteImport.update({
  id: '/portail',
  path: '/portail',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TransmissionsRoute = TransmissionsRouteImport.update({
  id: '/transmissions',
  path: '/transmissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesSlugRoute = ModulesSlugRouteImport.update({
  id: '/modules/$slug',
  path: '/modules/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacieIndexRoute = PharmacieIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PharmacieRoute,
} as any)
const PharmacieChecklistRoute = PharmacieChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => PharmacieRoute,
} as any)
const PharmacieComparatifRoute = PharmacieComparatifRouteImport.update({
  id: '/comparatif',
  path: '/comparatif',
  getParentRoute: () => PharmacieRoute,
} as any)
const PharmacieFichesRoute = PharmacieFichesRouteImport.update({
  id: '/fiches',
  path: '/fiches',
  getParentRoute: () => PharmacieRoute,
} as any)
const PharmacieSignalementsRoute = PharmacieSignalementsRouteImport.update({
  id: '/signalements',
  path: '/signalements',
  getParentRoute: () => PharmacieRoute,
} as any)
const ApiPublicPharmaFichesCronRoute =
  ApiPublicPharmaFichesCronRouteImport.update({
    id: '/api/public/pharma-fiches-cron',
    path: '/api/public/pharma-fiches-cron',
    getParentRoute: () => rootRouteImport,
  } as any)
const PharmacieFicheSlugRoute = PharmacieFicheSlugRouteImport.update({
  id: '/fiche/$slug',
  path: '/fiche/$slug',
  getParentRoute: () => PharmacieRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/invite': typeof InviteRoute
  '/pharmacie': typeof PharmacieRouteWithChildren
  '/portail': typeof PortailRoute
  '/profile': typeof ProfileRoute
  '/transmissions': typeof TransmissionsRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/pharmacie/checklist': typeof PharmacieChecklistRoute
  '/pharmacie/comparatif': typeof PharmacieComparatifRoute
  '/pharmacie/fiches': typeof PharmacieFichesRoute
  '/pharmacie/signalements': typeof PharmacieSignalementsRoute
  '/pharmacie/': typeof PharmacieIndexRoute
  '/api/public/pharma-fiches-cron': typeof ApiPublicPharmaFichesCronRoute
  '/pharmacie/fiche/$slug': typeof PharmacieFicheSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/invite': typeof InviteRoute
  '/portail': typeof PortailRoute
  '/profile': typeof ProfileRoute
  '/transmissions': typeof TransmissionsRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/pharmacie/checklist': typeof PharmacieChecklistRoute
  '/pharmacie/comparatif': typeof PharmacieComparatifRoute
  '/pharmacie/fiches': typeof PharmacieFichesRoute
  '/pharmacie/signalements': typeof PharmacieSignalementsRoute
  '/pharmacie': typeof PharmacieIndexRoute
  '/api/public/pharma-fiches-cron': typeof ApiPublicPharmaFichesCronRoute
  '/pharmacie/fiche/$slug': typeof PharmacieFicheSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/invite': typeof InviteRoute
  '/pharmacie': typeof PharmacieRouteWithChildren
  '/portail': typeof PortailRoute
  '/profile': typeof ProfileRoute
  '/transmissions': typeof TransmissionsRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/pharmacie/checklist': typeof PharmacieChecklistRoute
  '/pharmacie/comparatif': typeof PharmacieComparatifRoute
  '/pharmacie/fiches': typeof PharmacieFichesRoute
  '/pharmacie/signalements': typeof PharmacieSignalementsRoute
  '/pharmacie/': typeof PharmacieIndexRoute
  '/api/public/pharma-fiches-cron': typeof ApiPublicPharmaFichesCronRoute
  '/pharmacie/fiche/$slug': typeof PharmacieFicheSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/invite'
    | '/pharmacie'
    | '/portail'
    | '/profile'
    | '/transmissions'
    | '/modules/$slug'
    | '/pharmacie/checklist'
    | '/pharmacie/comparatif'
    | '/pharmacie/fiches'
    | '/pharmacie/signalements'
    | '/pharmacie/'
    | '/api/public/pharma-fiches-cron'
    | '/pharmacie/fiche/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/invite'
    | '/portail'
    | '/profile'
    | '/transmissions'
    | '/modules/$slug'
    | '/pharmacie/checklist'
    | '/pharmacie/comparatif'
    | '/pharmacie/fiches'
    | '/pharmacie/signalements'
    | '/pharmacie'
    | '/api/public/pharma-fiches-cron'
    | '/pharmacie/fiche/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/invite'
    | '/pharmacie'
    | '/portail'
    | '/profile'
    | '/transmissions'
    | '/modules/$slug'
    | '/pharmacie/checklist'
    | '/pharmacie/comparatif'
    | '/pharmacie/fiches'
    | '/pharmacie/signalements'
    | '/pharmacie/'
    | '/api/public/pharma-fiches-cron'
    | '/pharmacie/fiche/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  InviteRoute: typeof InviteRoute
  PharmacieRoute: typeof PharmacieRouteWithChildren
  PortailRoute: typeof PortailRoute
  ProfileRoute: typeof ProfileRoute
  TransmissionsRoute: typeof TransmissionsRoute
  ModulesSlugRoute: typeof ModulesSlugRoute
  ApiPublicPharmaFichesCronRoute: typeof ApiPublicPharmaFichesCronRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacie': {
      id: '/pharmacie'
      path: '/pharmacie'
      fullPath: '/pharmacie'
      preLoaderRoute: typeof PharmacieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portail': {
      id: '/portail'
      path: '/portail'
      fullPath: '/portail'
      preLoaderRoute: typeof PortailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transmissions': {
      id: '/transmissions'
      path: '/transmissions'
      fullPath: '/transmissions'
      preLoaderRoute: typeof TransmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$slug': {
      id: '/modules/$slug'
      path: '/modules/$slug'
      fullPath: '/modules/$slug'
      preLoaderRoute: typeof ModulesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacie/': {
      id: '/pharmacie/'
      path: '/'
      fullPath: '/pharmacie/'
      preLoaderRoute: typeof PharmacieIndexRouteImport
      parentRoute: typeof PharmacieRoute
    }
    '/pharmacie/checklist': {
      id: '/pharmacie/checklist'
      path: '/checklist'
      fullPath: '/pharmacie/checklist'
      preLoaderRoute: typeof PharmacieChecklistRouteImport
      parentRoute: typeof PharmacieRoute
    }
    '/pharmacie/comparatif': {
      id: '/pharmacie/comparatif'
      path: '/comparatif'
      fullPath: '/pharmacie/comparatif'
      preLoaderRoute: typeof PharmacieComparatifRouteImport
      parentRoute: typeof PharmacieRoute
    }
    '/pharmacie/fiches': {
      id: '/pharmacie/fiches'
      path: '/fiches'
      fullPath: '/pharmacie/fiches'
      preLoaderRoute: typeof PharmacieFichesRouteImport
      parentRoute: typeof PharmacieRoute
    }
    '/pharmacie/signalements': {
      id: '/pharmacie/signalements'
      path: '/signalements'
      fullPath: '/pharmacie/signalements'
      preLoaderRoute: typeof PharmacieSignalementsRouteImport
      parentRoute: typeof PharmacieRoute
    }
    '/api/public/pharma-fiches-cron': {
      id: '/api/public/pharma-fiches-cron'
      path: '/api/public/pharma-fiches-cron'
      fullPath: '/api/public/pharma-fiches-cron'
      preLoaderRoute: typeof ApiPublicPharmaFichesCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacie/fiche/$slug': {
      id: '/pharmacie/fiche/$slug'
      path: '/fiche/$slug'
      fullPath: '/pharmacie/fiche/$slug'
      preLoaderRoute: typeof PharmacieFicheSlugRouteImport
      parentRoute: typeof PharmacieRoute
    }
  }
}

interface PharmacieRouteChildren {
  PharmacieChecklistRoute: typeof PharmacieChecklistRoute
  PharmacieComparatifRoute: typeof PharmacieComparatifRoute
  PharmacieFichesRoute: typeof PharmacieFichesRoute
  PharmacieSignalementsRoute: typeof PharmacieSignalementsRoute
  PharmacieIndexRoute: typeof PharmacieIndexRoute
  PharmacieFicheSlugRoute: typeof PharmacieFicheSlugRoute
}

const PharmacieRouteChildren: PharmacieRouteChildren = {
  PharmacieChecklistRoute: PharmacieChecklistRoute,
  PharmacieComparatifRoute: PharmacieComparatifRoute,
  PharmacieFichesRoute: PharmacieFichesRoute,
  PharmacieSignalementsRoute: PharmacieSignalementsRoute,
  PharmacieIndexRoute: PharmacieIndexRoute,
  PharmacieFicheSlugRoute: PharmacieFicheSlugRoute,
}

const PharmacieRouteWithChildren = PharmacieRoute._addFileChildren(
  PharmacieRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  InviteRoute: InviteRoute,
  PharmacieRoute: PharmacieRouteWithChildren,
  PortailRoute: PortailRoute,
  ProfileRoute: ProfileRoute,
  TransmissionsRoute: TransmissionsRoute,
  ModulesSlugRoute: ModulesSlugRoute,
  ApiPublicPharmaFichesCronRoute: ApiPublicPharmaFichesCronRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
